import {
  Box,
  UserRound,
  Wand2,
  Folder,
  Bot,
  Plug,
  Cpu,
  Sparkles,
  Database,
  BookOpen,
  List,
  Workflow,
  Radar,
  MessagesSquare,
  Laptop,
  Server,
  Send,
  MessageCircle,
  Sunrise,
  Route,
  Home,
  MessageSquare,
  Filter,
  Handshake,
  Share2,
  Clapperboard,
  Crosshair,
  Wallet,
  Users,
  ListChecks,
  Network,
  Brain,
  Waypoints,
  GitCompareArrows,
  Wrench,
  Map,
  BarChart3,
  LayoutGrid,
  Layers,
  Square,
  Terminal,
  LayoutDashboard,
  Globe,
  Play,
  HardDrive,
  RefreshCw,
  type LucideIcon,
} from 'lucide-react';

/**
 * The Blueprint icon language: node.icon (a plain string set by the
 * compiler) maps to a Lucide component here. Unknown names fall back to Box
 *: the canvas can never crash on an icon it doesn't recognize.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  box: Box,
  'user-round': UserRound,
  'wand-2': Wand2,
  folder: Folder,
  bot: Bot,
  plug: Plug,
  cpu: Cpu,
  sparkles: Sparkles,
  database: Database,
  'book-open': BookOpen,
  list: List,
  workflow: Workflow,
  radar: Radar,
  'messages-square': MessagesSquare,
  laptop: Laptop,
  server: Server,
  send: Send,
  'message-circle': MessageCircle,
  sunrise: Sunrise,
  route: Route,
  home: Home,
  'message-square': MessageSquare,
  filter: Filter,
  handshake: Handshake,
  'share-2': Share2,
  clapperboard: Clapperboard,
  crosshair: Crosshair,
  wallet: Wallet,
  users: Users,
  'list-checks': ListChecks,
  network: Network,
  brain: Brain,
  waypoints: Waypoints,
  'git-compare-arrows': GitCompareArrows,
  wrench: Wrench,
  map: Map,
  'bar-chart-3': BarChart3,
  'layout-grid': LayoutGrid,
  layers: Layers,
  square: Square,
  terminal: Terminal,
  'layout-dashboard': LayoutDashboard,
  globe: Globe,
  play: Play,
  'hard-drive': HardDrive,
  'refresh-cw': RefreshCw,
};

export function iconFor(name: string): LucideIcon {
  return ICON_MAP[name] ?? Box;
}
